apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: countdown
spec:
  schedule: "* * * * *"
  jobTemplate:
    metadata:
      name: countdown
    spec:
      template:
        spec:
          containers:
          - name: counter
            image: centos:7
            args:
             - "bin/bash"
             - "-c"
             - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
          restartPolicy: Never

