apiVersion: v1 # the api version to use
kind: Pod # for example: Pod
metadata:
  name: webservice01
spec:
  containers:
  - name: nginx # name of container
    image: nginx:1.7.9 # name of the image to use
    ports:
    - name: p8888 # name for port mapping
      containerPort: 8888 # we mapped this with the port-forward command
      protocol: TCP # TCP or UDP

